kind: pipeline
type: docker
name: default

workspace:
  path: /drone/src

steps:
  - name: Build
    pull: if-not-exists
    image: docker:latest
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - echo hello
      - docker build -t android-build:latest .

  - name: Run
    pull: if-not-exists
    image: docker:latest
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: code
        path: /home/gradle
    commands:
      - ls -al /drone/src
      - docker volume inspect drone
      - docker run --rm -v code:/home/gradle/ android-build ls -al /home/gradle
      - docker run --rm -v code:/home/gradle/ android-build gradle build

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: code
    host:
      path: /drone/src