kind: pipeline
type: docker
name: default

steps:
  - name: Build
    pull: if-not-exists
    image: docker:latest
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - echo hello
      - docker build -t android-build:latest .

  - name: Run
    pull: if-not-exists
    image: docker:latest
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker run --rm -v "$PWD":/home/gradle/ android-build gradle build

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock