kind: pipeline
type: docker
name: default

workspace:
  path: /drone/src

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: code
    host:
      path: /drone/src

steps:
  - name: Build
    pull: if-not-exists
    image: docker:latest
    commands:
      - docker build -t android-build:latest .
      - docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /drone/src:/home/gradle android-build gradle build
