kind: pipeline
type: docker
name: default

steps:
  - name: test
    pull: always
    image: docker:dind
    commands:
      - echo hello
      - docker build -t android-build:latest .
      - docker run --rm -v "$PWD":/home/gradle/ android-build gradle build