kind: pipeline
type: docker
name: default

workspace:
  path: /drone/src

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: code
    host:
      path: /drone/src

steps:
  - name: Build
    pull: if-not-exists
    image: docker:latest
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: code
        path: /home/gradle
    commands:
      - docker build -t android-build:latest .

  - name: Test
    pull: if-not-exists
    image: docker:latest
    volumes:
      - name: code
        path: /home/gradle
    commands:
      - docker volume ls

  - name: Run
    pull: if-not-exists
    image: docker:latest
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: code
        path: /home/gradle
    commands:
      - docker run --rm android-build gradle build
