image: docker:latest

stages:
  - build

docker_build:
  tags:
    - docker
  stage: build
  script:
    - docker build -t android-build:latest .
    - docker run --rm -v "$PWD":/home/gradle/ android-build gradle build
  variables:
    GIT_STRATEGY: none
