stages:
  - build

pre_clone_script = "sudo chown -R gitlab-runner:gitlab-runner ."

docker_build:
  tags:
    - shell
  stage: build
  script:
    - docker build -t android-build:latest .
    - docker run --rm -v "$PWD":/home/gradle/ android-build gradle build
